version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: sushilnitp
          password: Allahabad!123
    steps:
      - checkout
      - run: mvn test

  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: sushilnitp
          password: Allahabad!123
    steps:
      - checkout
      - run: mvn clean install

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build